python_tuts/django/todolist/todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [   
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

python_tuts/django/todolist/todos/urls.py
from django.urls import path

from . import views

app_name = 'todos'
urlpatterns = [    
    path('', views.index, name='index'),    
    path('details/<int:todo_id>/', views.details, name='details'),    
    #ex: /todos/add/
    path('add/', views.add, name='add')
]

python_tuts/django/todolist/todos/models.py
from django.db import models
from datetime import datetime

# Create your models here.
class Todo( models.Model ):
    title = models.CharField(max_length=200)
    text = models.TextField()
    date = models.DateTimeField(default=datetime.now, blank = True)
    def __str__( self ):
        return self.title

python_tuts/django/todolist/todos/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Todo

# Create your views here.
def index( request ):
    todos = Todo.objects.all()[:10]
    context = {
        'todos': todos
    }
    return render(request, 'todos/index.html', context)

def details( request, todo_id ):
    todo = Todo.objects.get(id=todo_id)
    context = {
        'todo': todo
    }
    return render(request, 'todos/details.html', context)

def add( request ):
    if(request.method == 'POST'):
        title = request.POST['title']
        text = request.POST['text']

        todo = Todo(title = title, text = text)
        todo.save()

        return redirect('/todos')
    else:
        return render(request, 'todos/add.html')

python_tuts/django/todolist/todos/templates/todos/add.html
{% include 'todos/partials/header.html' %}
<form action="{% url 'todos:add' %}" method="POST">
{% csrf_token %}
  <label for="title">Title</label><br />
  <input type="text" name="title" id="title" />
  <br>
  <label for="text">Text</label><br />
  <textarea name="text" id="text"></textarea>
  <br><br>
  <input type="submit" value="Submit" />
</form>
<br>
<a href="/todos">Go Back</a>
{% include 'todos/partials/footer.html' %}

python_tuts/django/todolist/todos/templates/todos/details.html
{% include 'todos/partials/header.html' %}
<a href="/todos"><< Go Back</a>
<br>
<h1>{{todo.title}}</h1>
<p>{{todo.text}}</p>
<br>
Created on {{todo.date}}
{% include 'todos/partials/footer.html' %}

python_tuts/django/todolist/todos/templates/todos/index.html
{% include 'todos/partials/header.html'%}
    <ul>
      {% for todo in todos %}
        <li><a href="/todos/details/{{todo.id}}">{{todo.title}}</a>: {{todo.text}}</li>
      {% endfor %}
    </ul>
{% include 'todos/partials/footer.html'%}

python_tuts/django/todolist/todos/templates/todos/partials/footer.html
</body>
</html>

python_tuts/django/todolist/todos/templates/todos/partials/header.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load static %}
    <link rel="stylesheet" href="{% static 'todos/css/style.css' %}">
    <title>TodoList</title>
  </head>
  <body>
    <header>
      <h1>TodoList</h1>
      <a href="/todos/add">Add Todo</a>
      <hr>
</header>